modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/KMN64/Immersive-Mechanical/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/KMN64/Immersive-Mechanical"
logoFile="${mod_id}logo.png"
credits="Kmn64"
authors="${mod_authors}"
description=${mod_description}
[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[${minecraft_version}-5.1.0-148,)"
	ordering="BEFORE"
	side="BOTH"
