name: Build IM

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-
            
            - name: Setup JDK 8
              uses: actions/setup-java@v3
              with:
                java-version: 8
                distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 8.6
            - name: Compile IM
              run: ./gradlew --max-workers 1 compileJava
            - name: Build IM
              run: ./gradlew --max-workers 1 build
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                name: mod-jar
                path: build/libs/*.jar


            