name: Compile IM

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: ~/.gradle/caches
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-
            
            - name: Setup JDK 8
              uses: actions/setup-java@v3
              with:
                java-version: 8
                distribution: 'temurin'

            - name: Setup Gradle
              run: chmod +x gradlew
            - name: Compile IM
              run: ./gradlew --max-workers 1 compileJava
            - name: Compile Datagen
              run: ./gradlew --max-workers 1 runData || true
            - name: Check for crashes
              run: bash -c "[ -f run-data/im_datagen_done ]"


            